import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import Idiomas from '../components/Idiomas'
import {
  IconClose,
  IconMenu,
  IconSettings,
  IconSpeaker,
  IconUser,
  IconWhatsapp
} from '../icons'
// import styles from '../../styles/Home.module.css'

export default function Home(props) {
  const [isModal, setisModal] = useState(false)
  const [isMenu, setIsMenu] = useState(false)
  const [isSettings, setIsSettings] = useState(false)
  const { titulo, TextButton } = props.Inicio
  const { campo1, campo2, textButton, textPassword } = props.ModalInicio

  return (
    <>
      <Head>
        {/* <link rel="shortcut icon" href="logo.png" type="image/x-icon" /> */}
        <title>OVUM</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <main className="relative overflow-hidden">
        <div className="home w-full relative">
          <header className="px-4 md:px-[52px] flex justify-between items-start flex-row-reverse pt-8 md:items-center">
            {/* Text  */}
            <h3 className="text-center text-white font-light text-xl md:text-[25px] leading-[30.26px] tracking-widest order-3 md:order-2 z-20 mr-4">
              {titulo}
            </h3>

            {/* Group */}
            <div className="flex items-center gap-x-4 flex-row-reverse sm:flex-row">
              {/* Icon sonido */}
              <IconSpeaker className="speaker text-white w-[25px] h-[20px] order-1 z-20  md:mb-0 cursor-pointer " />
              {/* Ingresar */}
              <IconUser
                className="w-[25px] h-[27px] mr-1 order-2 md:order-3 cursor-pointer z-20 hover:translate-y-[-4px] transition-all duration-500 "
                onClick={() => setisModal(true)}
              />
              <IconSettings
                className="text-white w-[25px] h-[25px] cursor-pointer hover:rotate-[30deg] transition-transform duration-500 sm:hidden"
                onClick={() => setIsSettings(!isSettings)}
              />
              {/* Idiomas */}
              <div
                className={`absolute bg-primary-100 ${
                  isSettings ? 'right-4' : 'right-[-100%]'
                } top-20 rounded-[8px] pl-2 transition-right duration-1000 sm:static sm:bg-transparent sm:pl-0 z-50`}
              >
                <Idiomas idiomas={props} />
              </div>
            </div>

            {/* IconMenu */}
            {/* <IconMenu
              className="text-white w-[80px] h-[45px] cursor-pointer z-30 md:hidden"
              onClick={() => setIsMenu(!isMenu)}
            /> */}
          </header>

          {/* Footer */}
          <button
            className="btn  w-[200px] h-[35px] md:w-[220px] md:h-[45px] text-white bg-primary-100 flex items-center justify-center text-base md:text-[20px] leading-[27px] font-open font-semibold tracking-widest absolute bottom-[80px] md:bottom-[60px] mx-auto right-0 left-0 "
            id="showButton"
            onClick={() => setisModal(true)}
          >
            {TextButton}
          </button>
          {/* <p
      class="absolute left-6 md:left-[75px] bottom-7 font-open text-xs md:text-base leading-[22px] tracking-widest text-white z-20">
      SAN PEDRO
      SULA - HONDURAS</p>  */}

          <Link
            href="https://api.whatsapp.com/send?phone=3158521478&text=Entre%20a%20la%20feria"
            target="_blank"
          >
            <a>
              <IconWhatsapp className="cursor-pointer absolute z-20 bottom-[19px] left-6 md:left-[75px] w-[56px] h-[56px]  md:w-[96px] md:h-[96px] hover:translate-y-[-8px] transition-all duration-500" />
            </a>
          </Link>
        </div>
      </main>

      {/* Modal  */}
      <div
        id="modal"
        className={`bg-opacity absolute top-0 right-0 bottom-0 left-0 z-10  justify-center items-center ${
          isModal ? 'flex' : 'hidden'
        }`}
      >
        <div className="w-[350px] sm:w-[393px]  bg-white rounded-[13px] pt-[15px] pr-[22px] pb-[22px] pl-[20px] relative">
          <IconClose
            className="w-6 h-6 absolute top-1 right-1 cursor-pointer"
            onClick={() => setisModal(false)}
          />
          <div className="relative w-[300px] h-[150px]  sm:w-[350px] sm:h-[167px] mb-[15px]">
            <Image
              src="/image/image-modal.png"
              className="w-full h-[full "
              layout="fill"
              alt="logo-modal"
            />
          </div>
          <form id="form" className=" flex flex-col items-center ">
            <div className="mb-[14.84px] flex">
              <label
                forhtml=""
                className="text-[15px] font-light leading-[21px] mr-9 font-open"
              >
                {campo1}
              </label>
              <input
                type="email"
                className="w-[231px] h-[34px] border-[0.8px] border-[#C4C4C4] rounded-[8.7px] pl-4 focus:border-[0.8px] focus:border-primary-100 outline-none"
              />
            </div>
            <div className="mb-[28.8px] flex">
              <label
                forhtml=""
                className="text-[15px] font-light leading-[21px] mr-[10px] font-open"
              >
                {campo2}
              </label>
              <input
                type="password"
                className="w-[231px] h-[34px] border-[0.8px] border-[#C4C4C4] rounded-[8.7px] pl-4 focus:border-[0.8px] focus:border-primary-100 outline-none"
              />
            </div>
            <Link href="/lobby">
              <a
                type="submit"
                className="btn bg-primary-100 w-[130px] h-[30px] flex justify-center items-center text-white font-normal leading-[21px] font-open tracking-widest text-[15px] mx-auto rounded-xl mb-[10px] cursor-pointer"
              >
                {textButton}
              </a>
            </Link>

            <Link href="/recuperar">
              <a className="text-center text-[15px] font-light leading-[21px] font-open cursor-pointer hover:text-primary-100">
                {textPassword}
              </a>
            </Link>
          </form>

          <p className="text-[#D91A15] text-center leading-[21px] text-[17px] font-light mt-5 hidden">
            Los datos que ingresaste son incorrectos, intentalo de nuevo
          </p>
        </div>
      </div>
    </>
  )
}
export async function getStaticProps({ locale }) {
  const response = await import(`../lang/${locale}.json`)

  return {
    props: {
      HeaderIdiomas: response.default.HeaderIdiomas,
      Inicio: response.default.Inicio,
      ModalInicio: response.default.ModalInicio
    }
  }
}
